site_name: SEEWAVE
nav:
    - Home: home.md
    - Asclepius: index.md
    - TT system: tt.md
    - Contact us: about.md
    - Refference: refference.md
#theme: windmill
theme: readthedocs
#theme:
#  name: 'material'