site_name: SEEWAVE
nav:
    - Home: home.md
    - Asclepius: index.md
    - TT system: tt.md
#theme: windmill
#theme: readthedocs
copyright: 'Copyright &copy; 2018 - 2019 SEEWAVE'

theme:
  name: 'material'
  #palette:
    #primary: 'amber'
    #accent: 'amber'
  #font:
    #text: 'Roboto'
    #code: 'Roboto Mono'
  #logo: 'images/copper_logo.svg'
  #language: 'en'
  #favicon: 'images/favicon.ico'