site_name: SEEWAVE
nav:
    - Home: index.md
    - Asclepius: asclepius.md
    - TT system: tt.md
    - Contact us: about.md
    - Refference: refference.md
#theme: windmill
theme: readthedocs
#theme:
#  name: 'material'